### Numpy

In [54]:
import numpy as np
list_numbers=[2, 4, 6, 8, 10, 12, 14, 16]
# 1
res=np.array(list_numbers)
print(res)

[ 2  4  6  8 10 12 14 16]


In [55]:
n=2**8
print(n)
temp=0
for i in range(1,8):
    temp*=2*i
print(temp)
print(pow(2,8))



256
0
256


In [56]:
import math as mp
print(mp.sqrt(25)) 
print(mp.pow(2,4))
print(mp.factorial(5))
print(mp.cos(45))
print(mp.gcd(12,18))
print(mp.log10(100))
print(mp.log(1000,10))
print(mp.lcm(12, 18))
print(mp.exp(3))
print(mp.pi)
print(mp.degrees(4))
print(mp.e)
print(mp.fabs(63.123123))
print(mp.perm(10,20))

print(mp.exp2(8))
# print(mp.sin(radia))
p = (1, 2)
q = (4, 6)
print(mp.dist(p, q))



5.0
16.0
120
0.5253219888177297
6
2.0
2.9999999999999996
36
20.085536923187668
3.141592653589793
229.1831180523293
2.718281828459045
63.123123
0
256.0
5.0


In [ ]:
import os
os.mkdir("DMDW_Experiment_3")



In [58]:
import numpy as np
list1=[[1,4,5,6],[8,5,10,11]]
print(list1)
print(np.array(list1))



[[1, 4, 5, 6], [8, 5, 10, 11]]
[[ 1  4  5  6]
 [ 8  5 10 11]]


In [59]:
import numpy as np
from scipy import stats
list1=np.array([1,4,5,6,8,5,10,11])

print(np.searchsorted(list1,5))
#1 slicing array
print(list1[1:5])
# 2 splitting array
split=np.split(list1,2)
print(split)
# 3 combining array
combined=np.concatenate((list1,list1))
print(combined)
# 4 mean,max,median,mode
print(np.min(list1))
print(np.mean(list1))
print(np.max(list1))
print(np.median(list1))

arr = np.array([[1, 4, 5, 6, 8], [5, 10, 11, 3, 34]])
print(stats.mode(arr, axis=None, keepdims=True))


2
[4 5 6 8]
[array([1, 4, 5, 6]), array([ 8,  5, 10, 11])]
[ 1  4  5  6  8  5 10 11  1  4  5  6  8  5 10 11]
1
6.25
11
5.5
ModeResult(mode=array([[5]]), count=array([[2]]))



2.1 Numpy 
Problem: Given a list of numbers [2, 4, 6, 8, 10, 12, 14, 16], perform the following tasks using NumPy 
functions: 
Create a NumPy array from the given list. 
Calculate the mean, median, and standard deviation of the array. 
Reshape the array into a 2x4 matrix. 
Calculate the element-wise square root of the array. 
Find the index of the maximum element in the array. 
Create a new array containing only the elements greater than 8.


In [60]:
import numpy as np
list_numbers=[2, 4, 6, 8, 10, 12, 14, 16]

arr=np.array(list_numbers)
print("Original NumPy Array:\n", arr)

print("\nStatistical Measures:")
print("Mean :", np.mean(arr))
print("Median :", np.median(arr))
print("Standard Deviation :", np.std(arr))
print("Reshaped Array (2x4):\n",np.reshape(arr,(2,4)))
print("Element-wise Square Root:\n",np.sqrt(arr))
print("Index of the max element: ",np.argmax(arr))
print("Elements Greater Than 8:\n",arr[arr>8])

Original NumPy Array:
 [ 2  4  6  8 10 12 14 16]

Statistical Measures:
Mean : 9.0
Median : 9.0
Standard Deviation : 4.58257569495584
Reshaped Array (2x4):
 [[ 2  4  6  8]
 [10 12 14 16]]
Element-wise Square Root:
 [1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162
 3.74165739 4.        ]
Index of the max element:  7
Elements Greater Than 8:
 [10 12 14 16]


In [61]:
import pandas as pd
import numpy as np
age=np.array([48,52,19])
# series1=pd.Series(age)
series1=pd.Series(age,index=['Ram','Hari','Som'])
print(series1)

Ram     48
Hari    52
Som     19
dtype: int64


In [62]:
import pandas as pd
data=[['Ram',30,'ECE'],['Situ',45,'CSE'],['Ram',30,'AIML']]
columns = ['Name', 'Age', 'Department']
dataF=pd.DataFrame(data,columns=columns)
dataF_indexed=dataF.set_index('Name')
print("Original DataFrame (Before)\n",dataF)
# index is there at the starting
print("\nDataFrame with 'Name' as an index")
print(dataF_indexed)

Original DataFrame (Before)
    Name  Age Department
0   Ram   30        ECE
1  Situ   45        CSE
2   Ram   30       AIML

DataFrame with 'Name' as an index
      Age Department
Name                
Ram    30        ECE
Situ   45        CSE
Ram    30       AIML


2.2 Pandas:
Consider the following data about employees in a company:

Name	Age	Department	Salary
Alice	28	HR		50000
Bob	22	Engineering	60000
Charlie	35	HR		55000
David	30	Engineering	62000
Eve	25	Finance		45000

1.Create a Pandas DataFrame to store the given data.
2.Display the basic information about the DataFrame (e.g., number of rows, columns, data types, and memory usage).
3. Calculate the average salary of employees.
4. Find the maximum age of employees in the Engineering department.
5. Display the names of employees who have a salary greater than 50000.
6. Add a new employee "Frank" to the DataFrame with Age 40, Department as "Finance," and Salary 55000.
7. Remove the employee named "Eve" from the DataFrame.


In [63]:
import pandas as pd

# 1 creating the dataframe 
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [28, 22, 35, 30, 25],
    'Department': ['HR', 'Engineering', 'HR', 'Engineering', 'Finance'],
    'Salary': [50000, 60000, 55000, 62000, 45000]
}
dataf = pd.DataFrame(data)
print("Initial Employee DataFrame:\n", dataf)



Initial Employee DataFrame:
       Name  Age   Department  Salary
0    Alice   28           HR   50000
1      Bob   22  Engineering   60000
2  Charlie   35           HR   55000
3    David   30  Engineering   62000
4      Eve   25      Finance   45000


In [64]:
# 2 basic display
print("Basic DataFrame Info:\n")
dataf.info()

Basic DataFrame Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        5 non-null      object
 1   Age         5 non-null      int64 
 2   Department  5 non-null      object
 3   Salary      5 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes


In [65]:
# 3 avg salary
average_salary = dataf['Salary'].mean()
print("\nAverage Salary of Employees:", average_salary)


Average Salary of Employees: 54400.0


In [66]:
# 4 max age in Engineering Department
max_age_engineering = dataf[dataf['Department'] == 'Engineering']['Age'].max()
print("\nMaximum Age in Engineering Department:", max_age_engineering)


Maximum Age in Engineering Department: 30


In [67]:
# 5 Salary > 50000
high_salary_employees = dataf[dataf['Salary'] > 50000]['Name']
print("\nEmployees with Salary > 50000:\n", high_salary_employees.to_list())


Employees with Salary > 50000:
 ['Bob', 'Charlie', 'David']


In [68]:
# 6 Add a new employee "Frank" 
new_employee = pd.DataFrame({
    'Name': ['Frank'],
    'Age': [40],
    'Department': ['Finance'],
    'Salary': [55000]
})
dataf = pd.concat([dataf, new_employee], ignore_index=True)
print("\n DataFrame After Adding 'Frank':\n", dataf)



 DataFrame After Adding 'Frank':
       Name  Age   Department  Salary
0    Alice   28           HR   50000
1      Bob   22  Engineering   60000
2  Charlie   35           HR   55000
3    David   30  Engineering   62000
4      Eve   25      Finance   45000
5    Frank   40      Finance   55000


In [69]:

# 7 Removing  "Eve"
dataf = dataf[dataf['Name'] != 'Eve']
print("\nDataFrame After Removing 'Eve':\n", dataf)


DataFrame After Removing 'Eve':
       Name  Age   Department  Salary
0    Alice   28           HR   50000
1      Bob   22  Engineering   60000
2  Charlie   35           HR   55000
3    David   30  Engineering   62000
5    Frank   40      Finance   55000
