### Numpy

In [15]:
import numpy as np
list_numbers=[2, 4, 6, 8, 10, 12, 14, 16]
# 1
res=np.array(list_numbers)
print(res)

[ 2  4  6  8 10 12 14 16]


In [16]:
n=2**8
print(n)
temp=0
for i in range(1,8):
    temp*=2*i
print(temp)
print(pow(2,8))



256
0
256


In [17]:
import math as mp
print(mp.sqrt(25)) 
print(mp.pow(2,4))
print(mp.factorial(5))
print(mp.cos(45))
print(mp.gcd(12,18))
print(mp.log10(100))
print(mp.log(1000,10))
print(mp.lcm(12, 18))
print(mp.exp(3))
print(mp.pi)
print(mp.degrees(4))
print(mp.e)
print(mp.fabs(63.123123))
print(mp.perm(10,20))

print(mp.exp2(8))
# print(mp.sin(radia))
p = (1, 2)
q = (4, 6)
print(mp.dist(p, q))



5.0
16.0
120
0.5253219888177297
6
2.0
2.9999999999999996
36
20.085536923187668
3.141592653589793
229.1831180523293
2.718281828459045
63.123123
0
256.0
5.0


In [19]:
import os
os.mkdir("DMDW_Experiment_1")



In [12]:
import numpy as np
list1=[[1,4,5,6],[8,5,10,11]]
print(list1)
print(np.array(list1))



[[1, 4, 5, 6], [8, 5, 10, 11]]
[[ 1  4  5  6]
 [ 8  5 10 11]]


In [11]:
import numpy as np
from scipy import stats
list1=np.array([1,4,5,6,8,5,10,11])

print(np.searchsorted(list1,5))
#1 slicing array
print(list1[1:5])
# 2 splitting array
split=np.split(list1,2)
print(split)
# 3 combining array
combined=np.concatenate((list1,list1))
print(combined)
# 4 mean,max,median,mode
print(np.min(list1))
print(np.mean(list1))
print(np.max(list1))
print(np.median(list1))

arr = np.array([[1, 4, 5, 6, 8], [5, 10, 11, 3, 34]])
print(stats.mode(arr, axis=None, keepdims=True))


2
[4 5 6 8]
[array([1, 4, 5, 6]), array([ 8,  5, 10, 11])]
[ 1  4  5  6  8  5 10 11  1  4  5  6  8  5 10 11]
1
6.25
11
5.5
ModeResult(mode=array([[5]]), count=array([[2]]))


"""
2.1 Numpy 
Problem: Given a list of numbers [2, 4, 6, 8, 10, 12, 14, 16], perform the following tasks using NumPy 
functions: 
Create a NumPy array from the given list. 
Calculate the mean, median, and standard deviation of the array. 
Reshape the array into a 2x4 matrix. 
Calculate the element-wise square root of the array. 
Find the index of the maximum element in the array. 
Create a new array containing only the elements greater than 8.
"""

In [9]:
import numpy as np
list_numbers=[2, 4, 6, 8, 10, 12, 14, 16]

arr=np.array(list_numbers)
print(arr)

print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))

print(np.reshape(arr,(2,4)))

print(np.sqrt(arr))
print(np.argmax(arr))
print(arr[arr>8])

[ 2  4  6  8 10 12 14 16]
9.0
2
16
4.58257569495584
[[ 2  4  6  8]
 [10 12 14 16]]
[1.41421356 2.         2.44948974 2.82842712 3.16227766 3.46410162
 3.74165739 4.        ]
7
[10 12 14 16]


In [7]:
import pandas as pd
import numpy as np
age=np.array([48,52,19])
# series1=pd.Series(age)
series1=pd.Series(age,index=['Ram','Hari','Som'])
print(series1)

Ram     48
Hari    52
Som     19
dtype: int64


In [8]:
import pandas as pd
data=[['Ram',30,'ECE'],['Situ',45,'CSE'],['Ram',30,'AIML']]
columns = ['Name', 'Age', 'Department']
dataF=pd.DataFrame(data,columns=columns)
dataF_indexed=dataF.set_index('Name')
print("Original DataFrame (Before)\n",dataF)
# index is there at the starting
print("\nDataFrame with 'Name' as an index")
print(dataF_indexed)

Original DataFrame (Before)
    Name  Age Department
0   Ram   30        ECE
1  Situ   45        CSE
2   Ram   30       AIML

DataFrame with 'Name' as an index
      Age Department
Name                
Ram    30        ECE
Situ   45        CSE
Ram    30       AIML
